# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evg5ic_J7B0lzj76byYe-OTYh_AJtWIl
"""

# Install the lightkurve package (Required for Google Colab)
!pip install lightkurve

# Import the library
import lightkurve as lk

# 1. Search the NASA MAST archive for Kepler-10 light curves
# The 'author' parameter ensures we get the official Kepler mission pipeline data
search_result = lk.search_lightcurve("Kepler-10", author="Kepler")
print("Found Data:")
print(search_result)

# 2. Download the first file from the search results (Quarter 1 data)
lc = search_result[0].download()

# 3. Plot the raw, unedited light curve
lc.plot(title="Kepler-10: Raw Light Curve Data")

# 4. Clean the signal
# This removes empty data points (NaNs), flattens the long-term instrumental drift,
# and removes extreme outliers (flares or cosmic rays)
cleaned_lc = lc.remove_nans().flatten().remove_outliers()

# 5. Plot the cleaned, flat light curve ready for transit detection
cleaned_lc.plot(title="Kepler-10: Cleaned & Flattened Light Curve")

import numpy as np

# 1. Define the search space
# Kepler-10b is known to have a very short orbit. We tell the algorithm to
# search for orbital periods between 0.5 days and 5 days.
search_periods = np.linspace(0.5, 5, 10000)

# 2. Run the Box Least Squares algorithm
# This scans all 10,000 frequencies to find the one that best fits a repeating box shape.
periodogram = cleaned_lc.to_periodogram(method='bls', period=search_periods)

# 3. Plot the periodogram (The "Frequency Domain")
# A massive spike indicates the dominant frequency (the orbital period).
periodogram.plot(title="BLS Periodogram: Detecting the Orbital Frequency")

# 4. Extract the planetary parameters
best_period = periodogram.period_at_max_power
transit_time = periodogram.transit_time_at_max_power
duration = periodogram.duration_at_max_power

print(f"Algorithm Result:")
print(f"Orbital Period Detected: {best_period:.4f}")
print(f"Transit Duration: {duration:.4f}")

# 5. Phase Folding (The Scope Sync)
# Just like an oscilloscope syncing to a repeating signal, this stacks
# all the individual transits on top of each other to make the U-shape undeniable.
folded_lc = cleaned_lc.fold(period=best_period, epoch_time=transit_time)

# 6. Plot the final verification
folded_lc.plot(title="Phase-Folded Light Curve: Exoplanet Confirmed")

import lightkurve as lk
import numpy as np
import matplotlib.pyplot as plt

# 1. DEFINE THE FUNCTION (The Engine)
def process_star(star_id):
    print(f"--- Processing {star_id} ---")

    # The 'try' block attempts to run your code
    try:
        # Search and download only Quarter 1 data to speed up processing
        search = lk.search_lightcurve(star_id, author="Kepler", quarter=1)

        # If no data exists, stop and return to the loop
        if len(search) == 0:
            print(f"[!] No data found in archive for {star_id}. Skipping.\n")
            return

        lc = search.download()

        # Clean the signal
        cleaned = lc.remove_nans().flatten().remove_outliers()

        # Run BLS Algorithm (broadened search from 0.5 to 20 days)
        search_periods = np.linspace(0.5, 20, 5000)
        bls = cleaned.to_periodogram(method='bls', period=search_periods)
        best_period = bls.period_at_max_power
        transit_time = bls.transit_time_at_max_power

        # Fold the data
        folded = cleaned.fold(period=best_period, epoch_time=transit_time)

        # Plot and save the result as an image file
        ax = folded.scatter()
        ax.set_title(f"{star_id} - Detected Period: {best_period.value:.2f} days")

        # Save the graph to the Colab environment instead of just displaying it
        filename = f"{star_id}_transit.png"
        plt.savefig(filename)

        # CRITICAL: Clear the memory so Colab doesn't crash after 100 plots
        plt.close()

        print(f"[SUCCESS] Transit graphed and saved as {filename}\n")

    # The 'except' block catches any internet drops or math errors
    except Exception as error:
        print(f"[ERROR] Failed to process {star_id}. Reason: {error}\n")


# 2. DEFINE THE BATCH LIST (The Fuel)
# Start with a small list to test. Once it works, you can expand this to 100+.
star_batch = [
    "Kepler-10",
    "Kepler-22",
    "Kepler-XYZ", # This will trigger our fault-tolerance
    "Kepler-90"
]

# 3. RUN THE PIPELINE (The Ignition)
print("Initiating Pipeline...\n")
for star in star_batch:
    process_star(star)
print("Pipeline Complete.")